export const listProduct = [
    {
      id: 0,
      name: "Syltherine",
      subDescription: "Stylish caf chair",
      currentPrice: "Rp 2.500.000",
      originalPrice: "Rp 3.500.000",
      image: "./assets/images/products/Syltherine.png",
      badge: "-30%",
    },
    {
      id: 1,
      name: "Leviosa",
      subDescription: "Stylish caf chair",
      currentPrice: "Rp 2.500.000",
      originalPrice: null,
      image: "./assets/images/products/Leviosa.png",
      badge: null,
    },
    {
      id: 2,
      name: "Lolito",
      subDescription: "Luxury big sofa",
      currentPrice: "Rp 7.000.000",
      originalPrice: "Rp 8.000.000",
      image: "./assets/images/products/Lolito.png",
      badge: "-50%",
    },
    {
      id: 3,
      name: "Repira",
      subDescription: "Luxury big sofa",
      currentPrice: "Rp 500.000",
      originalPrice: null,
      image: "./assets/images/products/Repira.png",
      badge: "New",
    },
    {
      id: 4,
      name: "Grifo",
      subDescription: "Luxury big sofa",
      currentPrice: "Rp 500.000",
      originalPrice: null,
      image: "./assets/images/products/Grifo.png",
      badge: "New",
    },
    {
      id: 5,
      name: "Muggo",
      subDescription: "Luxury big sofa",
      currentPrice: "Rp 150.000",
      originalPrice: null,
      image: "./assets/images/products/Muggo.png",
      badge: "New",
    },
    {
      id: 6,
      name: "Pingky",
      subDescription: "Luxury big sofa",
      currentPrice: "Rp 7.000.000",
      originalPrice: "Rp 14.000.000",
      image: "./assets/images/products/Pingky.png",
      badge: "New",
    },
    {
      id: 7,
      name: "Potty",
      subDescription: "Luxury big sofa",
      currentPrice: "Rp 500.000",
      originalPrice: "Rp 1.000.000",
      image: "./assets/images/products/Potty.png",
      badge: "New",
    },
    {
      id: 8,
      name: "Syltherine",
      subDescription: "Stylish caf chair",
      currentPrice: "Rp 2.500.000",
      originalPrice: "Rp 3.500.000",
      image: "./assets/images/products/Syltherine.png",
      badge: "-30%",
    },
    {
      id: 9,
      name: "Leviosa",
      subDescription: "Stylish caf chair",
      currentPrice: "Rp 2.500.000",
      originalPrice: null,
      image: "./assets/images/products/Leviosa.png",
      badge: null,
    },
    {
      id: 10,
      name: "Lolito",
      subDescription: "Luxury big sofa",
      currentPrice: "Rp 7.000.000",
      originalPrice: "Rp 8.000.000",
      image: "./assets/images/products/Lolito.png",
      badge: "-50%",
    },
    {
      id: 11,
      name: "Repira",
      subDescription: "Luxury big sofa",
      currentPrice: "Rp 500.000",
      originalPrice: null,
      image: "./assets/images/products/Repira.png",
      badge: "New",
    },
    {
      id: 12,
      name: "Grifo",
      subDescription: "Luxury big sofa",
      currentPrice: "Rp 500.000",
      originalPrice: null,
      image: "./assets/images/products/Grifo.png",
      badge: "New",
    },
    {
      id: 13,
      name: "Muggo",
      subDescription: "Luxury big sofa",
      currentPrice: "Rp 150.000",
      originalPrice: null,
      image: "./assets/images/products/Muggo.png",
      badge: "New",
    },
    {
      id: 14,
      name: "Pingky",
      subDescription: "Luxury big sofa",
      currentPrice: "Rp 7.000.000",
      originalPrice: "Rp 14.000.000",
      image: "./assets/images/products/Pingky.png",
      badge: "New",
    },
    {
      id: 15,
      name: "Potty",
      subDescription: "Luxury big sofa",
      currentPrice: "Rp 500.000",
      originalPrice: "Rp 1.000.000",
      image: "./assets/images/products/Potty.png",
      badge: "New",
    },
    {
      id: 16,
      name: "Potty",
      subDescription: "Luxury big sofa",
      currentPrice: "Rp 500.000",
      originalPrice: "Rp 1.000.000",
      image: "./assets/images/products/Potty.png",
      badge: "New",
    },
  ];
const ListProducts = () => {

    return (
        <>
            <p>order</p>
        </>
    )
}

export default ListProducts;